apiVersion: v1
kind: Pod
spec:
  containers:
  - name: rust
    image: docker.jamf.build/rust:1.44.0
    tty: true
    command:
    - cat
  - name: github
    image: docker.jamf.build/ci/hub:2.14.2
    tty: true
    command:
    - cat
