name: github pages

on:
  push:
    branches:
      # Change the branch to `master` before merging!
      - docs

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup mdBook
        uses: ryankurte/action-mdbook@0.1.1
        with:
          inputDir: "docs"

      - run: mdbook build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/book